SELECT			
RECV.EXTERNAL_SA_ID			
,RECV.ID_RECV			
,RECV.CRET_DT			
,CASE 			
	WHEN RECV.CD_BUSE = 'GSS' THEN 'GAS'		
	WHEN RECV.CD_BUSE = 'ESU' THEN 'ELECTRICITY'
	WHEN RECV.CD_BUSE = 'TSS' THEN 'TELECOMS'
	WHEN RECV.CD_BUSE IN ('DAL','MOP','GSU') THEN 'METERING'
	ELSE ''	
	END																	BUSINESS_USE
,RECV.FIN_LIVE
,CASE
	WHEN SP.ID_SPTY IN ('GSP','EDK','SPG') THEN 'PREPAYMENT'
	WHEN RECV.CD_PMET IN ('DDB','DCA','CCA') THEN 'DD'
	WHEN RECV.CD_PMET IN ('DDV','DDA','DCV','SOR') THEN 'OTHER SECURED'
	WHEN RECV.CODE_PMED IS NOT NULL THEN 'OTHER SECURED'
	ELSE 'UNSECURED'
	END																	PAYMENT_METHOD			
,RECV.AMT			
			
FROM			
VMI_AGED_RECV_GD_YREND20												RECV
INNER JOIN
VCRO_SERV_ACCT															SA
ON RECV.ID_SA = SA.ID
INNER JOIN
VCRO_SERVICE_PLAN														SP
ON SA.ID_SP = SP.ID
			
WHERE			
RECV.CD_ATRO NOT IN ('BE','BEG','SYSB')			
AND RECV.CD_BUSE IN ('ESU','GSS','TSS','DAL','MOP','GSU')			
AND RECV.AMT > '0'
AND RECV.EXTERNAL_SA_ID = '401797050'



SELECT		
RECV.EXTERNAL_SA_ID			
,RECV.ID_RECV			
,RECV.CRET_DT
,CASE 			
	WHEN RECV.CD_BUSE = 'GSS' THEN 'GAS'		
	WHEN RECV.CD_BUSE = 'ESU' THEN 'ELECTRICITY'
	WHEN RECV.CD_BUSE = 'TSS' THEN 'TELECOMS'
	WHEN RECV.CD_BUSE IN ('DAL','MOP','GSU') THEN 'METERING'
	ELSE ''	
	END																	BUSINESS_USE
,RECV.FIN_LIVE
,CASE
	WHEN SP.ID_SPTY IN ('GSP','EDK','SPG') THEN 'PREPAYMENT'
	WHEN RECV.CD_PMET IN ('DDB','DCA','CCA') THEN 'DD'
	WHEN RECV.CD_PMET IN ('DDV','DDA','DCV','SOR') THEN 'OTHER SECURED'
	WHEN RECV.CODE_PMED IS NOT NULL THEN 'OTHER SECURED'
	ELSE 'UNSECURED'
	END																	PAYMENT_METHOD			
,SUM(RECV.AMT)															AMOUNT			
			
FROM			
VMI_AGED_RECV_GD_YREND20												RECV
INNER JOIN
VCRO_SERV_ACCT															SA
ON RECV.ID_SA = SA.ID
INNER JOIN
VCRO_SERVICE_PLAN														SP
ON SA.ID_SP = SP.ID
			
WHERE			
RECV.CD_ATRO NOT IN ('BE','BEG','SYSB')			
AND RECV.CD_BUSE IN ('ESU','GSS','TSS','DAL','MOP','GSU')			
AND RECV.AMT < '0'	
AND recv.EXTERNAL_SA_ID = '401797050'

GROUP BY
RECV.EXTERNAL_SA_ID			
,RECV.ID_RECV			
,RECV.CRET_DT
,CASE 			
	WHEN RECV.CD_BUSE = 'GSS' THEN 'GAS'		
	WHEN RECV.CD_BUSE = 'ESU' THEN 'ELECTRICITY'
	WHEN RECV.CD_BUSE = 'TSS' THEN 'TELECOMS'
	WHEN RECV.CD_BUSE IN ('DAL','MOP','GSU') THEN 'METERING'
	ELSE ''	
	END																	
,RECV.FIN_LIVE
,CASE
	WHEN SP.ID_SPTY IN ('GSP','EDK','SPG') THEN 'PREPAYMENT'
	WHEN RECV.CD_PMET IN ('DDB','DCA','CCA') THEN 'DD'
	WHEN RECV.CD_PMET IN ('DDV','DDA','DCV','SOR') THEN 'OTHER SECURED'
	WHEN RECV.CODE_PMED IS NOT NULL THEN 'OTHER SECURED'
	ELSE 'UNSECURED'
	END																	


