DECLARE @MONTHEND														DATETIME
SET @MONTHEND = ('2020-05-31 23:59:59.998')

SELECT
SA.EXTERNAL_SA_ID
,BLPE.BILG_PERD
,SAST.BILG_STRT_DT
,SAST.BILG_END_DT
,SA.CD_BUSE
,SAST.ID_BLFR_01
,SSPF.BLLG_DESCR_SPCO
,CASE
	WHEN SSPF.BLLG_DESCR_SPCO LIKE 'STANDING%' THEN '0'
	ELSE SSPF.USAGE END													USAGE
,SSPF.AMT

FROM
VCRO_SAS_SP_FIN															SSPF
INNER JOIN
VCRO_SA_STATEMENT														SAST
ON SSPF.ID_SA = SAST.ID_SA AND SSPF.SEQ_NUM_SASM = SAST.SEQ_NUM
INNER JOIN
VCRO_SERV_ACCT															SA
ON SAST.ID_SA = SA.ID AND SSPF.ID_SA = SA.ID
INNER JOIN
VCRO_BILLING_PERD														BLPE
ON SAST.DBID_BLPE = BLPE.DBID
INNER JOIN
VCRO_CA_SERV_ACCT														CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT														CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND																BRD
ON CA.CD_BRND = BRD.CD

WHERE
SAST.STAT_CD = 'E'
AND SA.CD_BUSE IN ('ESU','GSS')
AND SAST.CRET_DT <= @MONTHEND
AND SSPF.BLLG_DESCR_SPCO NOT LIKE 'FIT%'
AND SSPF.AMT > '0'
AND BRD.CD_ATRO NOT IN ('BE','BEG')

ORDER BY
SA.EXTERNAL_SA_ID