DECLARE @YEAR															CHAR(4)
DECLARE @PERIOD															CHAR(2)
SET @YEAR = '2021'
SET @PERIOD = '01'

SELECT
SALES.FIN_YEAR
,SALES.MONTH
,SALES.BUS_USE
,SALES.CD_ATRO
,SALES.BILL_FREQ
,SALES.SERVICE_PLAN
,SALES.JOB_NUMBER														BSV
,SALES.COST_CENTRE
,SALES.ACCOUNT_CODE
,PERD.BILG_PERD
,SUM(SALES.UNITS)														USAGE
,SUM(SALES.REVENUE)														REVENUE

FROM
VMI_SALES_REPORT_DETAIL													SALES
INNER JOIN
VCRO_BILLING_PERD														PERD
ON SALES.BILL_PERIOD_KEY = PERD.DBID
INNER JOIN
VRT_VCRO_SERV_ACCT														SA
ON SALES.ID_SA = SA.ID

WHERE
SALES.FIN_YEAR = @YEAR
AND SALES.MONTH = @PERIOD
AND PERD.FIN_DT < (
				SELECT DATEADD(D,-10,MIN(AP.STRT_DT)) 
				FROM VCRO_ACCT_PERIOD AP 
				WHERE AP.YR_NUM = @YEAR AND AP.PERD_NUM = @PERIOD
				)
AND SALES.BUS_USE IN ('GSS','ESU')

GROUP BY
SALES.FIN_YEAR
,SALES.MONTH
,SALES.BUS_USE
,SALES.CD_ATRO
,SALES.BILL_FREQ
,SALES.SERVICE_PLAN
,SALES.JOB_NUMBER	
,SALES.COST_CENTRE
,SALES.ACCOUNT_CODE
,PERD.BILG_PERD