SELECT
MCC.YR_NUM_ACPE_01
,MCC.PERD_NUM_ACPE_01
,MCC.APPROVAL_DATE
,MCC.EXTERNAL_SA_ID
,FAIT.DESCR
,MCC.ORIGINATOR_ID
,MCC.APPROVAL_ID
,MCC.ACCOUNT_CODE
,MCC.COST_CENTRE
,AMT

FROM
VMI_SALES_MCC		MCC
INNER JOIN
VCRO_FA_ITEM_TYPE	FAIT
ON MCC.CD_FAIT = FAIT.CD

WHERE
MCC.YR_NUM_ACPE_01 = '2020'
AND MCC.PERD_NUM_ACPE_01 = '09'
AND MCC.CD_ATRO NOT IN ('BE','BEG')
AND MCC.CD_BUSE IN ('ESU','GSS')
AND (
	MCC.COST_CENTRE IN ('9066','9077','9367','2666','2676')
	OR FAIT.DESCR LIKE '%REV%PRO%'
	)
