USE tempdb
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#WRITE_OFF') AND TYPE = 'U') DROP TABLE #WRITE_OFF
USE MIS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @INPUT_YEAR																			CHAR(4)
DECLARE @INPUT_PERIOD																		SMALLINT
DECLARE @WRITEOFF_START																		DATE
DECLARE @WRITEOFF_END																		DATE

SET @INPUT_YEAR =																			'2020'
SET @INPUT_PERIOD =																			'01'

SET @WRITEOFF_START =																		(SELECT MIN(STRT_DT)
																							FROM VCRO_ACCT_PERIOD
																							WHERE YR_NUM = @INPUT_YEAR AND PERD_NUM = @INPUT_PERIOD)
SET @WRITEOFF_END = 																		(SELECT MAX(CLO_DT)
																							FROM VCRO_ACCT_PERIOD
																							WHERE YR_NUM = @INPUT_YEAR AND PERD_NUM = @INPUT_PERIOD)

SELECT																						
COLC.ID_CRAC
,SA.EXTERNAL_SA_ID
,SA.TRUE_BAL_AMT																			SA_TRUE_BALANCE
,SA.SVC_BAL_AMT																				LAST_SA_BALANCE
,COLE.DEBT_VALUE
,COLC.CLO_DT																				CC_CLOSE_DT
,COLE.DISP_CRET_DT																			COLLECTIONS_EVENT_DATE
,EVDS.TXT																					COLLECTIONS_EVENT
,RECV.DISP_CRET_DT																			RECEIVABLE_DATE
,RECV.ORIG_BAL_AMT																			ORIGINAL_RECEIVABLE
,RECV.CUR_BAL_AMT																			CURRENT_RECEIVABLE

INTO #WRITE_OFF

FROM
VCRO_COLL_CASE																				COLC
INNER JOIN
VCRO_CC_DEBT_ASSOC																			CCDA
ON COLC.ID_CRAC = CCDA.ID_CRAC AND COLC.OPN_DT = CCDA.OPN_DT_COCE
INNER JOIN
VCRO_COLL_EVENT																				COLE
ON COLC.ID_CRAC = COLE.ID_CRAC AND COLC.OPN_DT = COLE.OPN_DT_COCE
INNER JOIN
VCRO_EVNT_DES																				EVDS
ON COLE.DBID_EVDS = EVDS.DBID
INNER JOIN
VCRO_CA_SERV_ACCT																			CASA
ON COLC.ID_CRAC = CASA.ID_CRAC
INNER JOIN
VRT_VCRO_SERV_ACCT																			SA
ON CASA.ID_SA = SA.ID
INNER JOIN
VCRO_RECEIVABLE																				RECV
ON CCDA.ID_RECV = RECV.ID AND SA.ID = RECV.ID_SA

WHERE
EVDS.TXT LIKE '%WRITE%'
AND SA.TRUE_BAL_AMT = '0'
AND COLE.DISP_CRET_DT BETWEEN @WRITEOFF_START AND @WRITEOFF_END

SELECT
@INPUT_YEAR																					YEAR
,@INPUT_PERIOD																				PERIOD
,CASE
	WHEN DATEDIFF(M,WOFF.RECEIVABLE_DATE,WOFF.COLLECTIONS_EVENT_DATE) < '0' THEN '0'
	WHEN DATEDIFF(M,WOFF.RECEIVABLE_DATE,WOFF.COLLECTIONS_EVENT_DATE) > '36' THEN '36'
	ELSE DATEDIFF(M,WOFF.RECEIVABLE_DATE,WOFF.COLLECTIONS_EVENT_DATE) END					LAG
,SUM(WOFF.ORIGINAL_RECEIVABLE)																ORIGINAL_RECEIVABLE

FROM
#WRITE_OFF																					WOFF

GROUP BY
CASE
	WHEN DATEDIFF(M,WOFF.RECEIVABLE_DATE,WOFF.COLLECTIONS_EVENT_DATE) < '0' THEN '0'
	WHEN DATEDIFF(M,WOFF.RECEIVABLE_DATE,WOFF.COLLECTIONS_EVENT_DATE) > '36' THEN '36'
	ELSE DATEDIFF(M,WOFF.RECEIVABLE_DATE,WOFF.COLLECTIONS_EVENT_DATE) END	