--****** THIS QUERY DOESN'T SEEM TO WORK PROPERLY WHEN IT COMES TO JOINING DEBITS AND CREDITS TOGETHER. BE CAREFUL.



SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

USE tempdb
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID ('#DR_FCLU') AND TYPE = 'U') DROP TABLE #DR_FCLU
IF EXISTS (SELECT * FROM SYS.objects WHERE OBJECT_ID = OBJECT_ID ('#CR_FCLU') AND TYPE = 'U') DROP TABLE #CR_FCLU
USE MIS

CREATE TABLE #DR_FCLU (
FAT_DESCR					VARCHAR(30)
,FAIT_DESCR					VARCHAR(30)
,CRITERIA_1					CHAR(10)
,CRITERIA_2					CHAR(10)
,CRITERIA_3					CHAR(10)
,DB_CR						CHAR(1)
,GL_CODE					VARCHAR(33)
)

INSERT INTO #DR_FCLU

SELECT
FAT.DESCR					
,COALESCE(FAIT.DESCR,'')	
,FCLU.SEARCH_1
,FCLU.SEARCH_2
,FCLU.SEARCH_3
,FCLU.DB_CR
,RTRIM(FC.GL_CODE)

FROM
VCRO_FC_LOOKUP				FCLU
INNER JOIN
VCRO_FIN_CODE				FC
ON FCLU.DBID_FC = FC.DBID
INNER JOIN
VCRO_FIN_ACT_TYP			FAT
ON FCLU.CD_FAAT = FAT.CD
LEFT OUTER JOIN
VCRO_FA_ITEM_TYPE			FAIT
ON FCLU.CD_FAIT = FAIT.CD


WHERE
FCLU.END_DT = '9999-12-31'
AND FCLU.DB_CR = 'D'

CREATE TABLE #CR_FCLU (
FAT_DESCR					VARCHAR(30)
,FAIT_DESCR					VARCHAR(30)
,CRITERIA_1					CHAR(10)
,CRITERIA_2					CHAR(10)
,CRITERIA_3					CHAR(10)
,DB_CR						CHAR(1)
,GL_CODE					VARCHAR(33)
)

INSERT INTO #CR_FCLU

SELECT
FAT.DESCR					
,COALESCE(FAIT.DESCR,'')	
,FCLU.SEARCH_1
,FCLU.SEARCH_2
,FCLU.SEARCH_3
,FCLU.DB_CR
,RTRIM(FC.GL_CODE)

FROM
VCRO_FC_LOOKUP				FCLU
INNER JOIN
VCRO_FIN_CODE				FC
ON FCLU.DBID_FC = FC.DBID
INNER JOIN
VCRO_FIN_ACT_TYP			FAT
ON FCLU.CD_FAAT = FAT.CD
LEFT OUTER JOIN
VCRO_FA_ITEM_TYPE			FAIT
ON FCLU.CD_FAIT = FAIT.CD

WHERE
FCLU.END_DT = '9999-12-31'
AND FCLU.DB_CR = 'C'

SELECT
DR.FAT_DESCR
,DR.FAIT_DESCR
,DR.CRITERIA_1
,DR.CRITERIA_2
,DR.CRITERIA_3
,DR.DB_CR
,DR.GL_CODE
,CR.CRITERIA_1
,CR.CRITERIA_2
,CR.CRITERIA_3
,CR.DB_CR
,CR.GL_CODE

FROM
#DR_FCLU					DR
INNER JOIN
#CR_FCLU					CR
ON DR.FAT_DESCR = CR.FAT_DESCR AND DR.FAIT_DESCR = CR.FAIT_DESCR