CREATE TABLE 
#DEBTS(
FIN_YEAR INT,
FIN_MONTH INT,
CATEGORY CHAR(24),
PAY_METHOD CHAR(10),
AGE CHAR(20),
FIN_LIVE CHAR(1),
CREDIT DECIMAL(10,2),
DEBIT DECIMAL(10,2))

INSERT INTO #DEBTS

SELECT
A.FIN_YEAR,
A.FIN_MONTH,
CASE
WHEN CD_ATRO = 'BE' THEN 'NON-DOMESTIC ELECTRICITY'
WHEN CD_BUSE = 'ESU' AND IBPT_CODE IS NOT NULL THEN 'NON-DOMESTIC ELECTRICITY'
WHEN CD_BUSE = 'ESU' AND IBPT_CODE IS NULL THEN 'DOMESTIC ELECTRICITY'
WHEN CD_ATRO = 'BEG' THEN 'NON-DOMESTIC GAS'
WHEN CD_BUSE = 'GSS' AND IBPT_CODE IS NOT NULL THEN 'NON-DOMESTIC GAS'
WHEN CD_BUSE = 'GSS' AND IBPT_CODE IS NULL THEN 'DOMESTIC GAS'
WHEN CD_BUSE = 'TSS' THEN 'TALK'
ELSE 'UNKNOWN'
END,
CASE
WHEN A.CD_PMET LIKE 'DD%' THEN 'DD'
WHEN A.ID_SP IN (SELECT ID FROM VCRO_SERVICE_PLAN WHERE DESCR LIKE '%TOKEN%' 
OR DESCR LIKE '%KEY%' OR DESCR LIKE '%PREPAYMENT%' OR DESCR LIKE '%PAY%') THEN 'PREPAYMENT'
ELSE 'OTHER'
END,
CASE
WHEN MO_AGE = 'M0' THEN '0-30 DAYS'
WHEN MO_AGE = 'M1' THEN '31-60 DAYS'
WHEN MO_AGE = 'M2' THEN '61-90 DAYS'
WHEN MO_AGE = 'M3' THEN '91-120 DAYS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q0' THEN '91-120 DAYS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q1' THEN '91-120 DAYS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q2' THEN '4-6 MONTHS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q3' THEN '7-9 MONTHS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q4' THEN '10-12 MONTHS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q4' AND YR_AGE = 'Y0' THEN '10-12 MONTHS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q5' AND YR_AGE = 'Y0' THEN '1-2 YEARS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q5' AND YR_AGE = 'Y1' THEN '1-2 YEARS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q5' AND YR_AGE = 'Y2' THEN '2-3 YEARS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q5' AND YR_AGE = 'Y3' THEN '3-4 YEARS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q5' AND YR_AGE = 'Y4' THEN '4-5 YEARS'
WHEN MO_AGE = 'M4' AND QT_AGE = 'Q5' AND YR_AGE = 'Y5' THEN '>5 YEARS'
ELSE MO_AGE
END AS AGE,
A.FIN_LIVE,
A.CR_FIN_TRANS_AMT,
A.DB_FIN_TRANS_AMT

FROM
VMI_SUM_AGED_RECV AS A

WHERE
A.CD_BUSE IN ('ESU','GSS','TSS')
AND A.FIN_YEAR = '2021'
AND A.FIN_MONTH = '01'

SELECT
FIN_YEAR,
FIN_MONTH,
CATEGORY,
PAY_METHOD,
AGE,
FIN_LIVE,
SUM(CREDIT) as "Credit_Total",
SUM(DEBIT) as "Debit_Total"

FROM
#DEBTS

WHERE
CATEGORY NOT LIKE 'NON-DOMESTIC%'

GROUP BY
FIN_YEAR,
FIN_MONTH,
CATEGORY,
PAY_METHOD,
AGE,
FIN_LIVE

DROP TABLE #DEBTS
