SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

USE tempdb
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#ACCTS') AND TYPE = 'U') DROP TABLE #ACCTS
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#RECEIVABLES') AND TYPE = 'U') DROP TABLE #RECEIVABLES
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#EXCEPTIONS') AND TYPE = 'U') DROP TABLE #EXCEPTIONS
USE MIS

CREATE TABLE #ACCTS			(
ID_SA						BIGINT
,ID_CRAC					INT
,EXTERNAL_SA_ID				INT
,CD_BUSE					CHAR(3)
,CD_ATRO					CHAR(4)
,BRAND_DESCR				VARCHAR(60)
,FIN_LIVE_IND				CHAR(8)
,TYP						CHAR(4)
,SECTOR						CHAR(4)
)

CREATE TABLE #RECEIVABLES	(
ID_RECV						BIGINT	
,ID_SA						BIGINT
,ID_PPLA					BIGINT
,AGE_QT						CHAR(16)
,AGED_ACTIVE_QT				CHAR(6)
,AGE_MO						CHAR(17)
,AGED_ACTIVE_MO				CHAR(6)
,CUR_BAL_AMT				DECIMAL(11,8)
,RUN_YEAR					CHAR(4)
,RUN_PERIOD					SMALLINT
							)

CREATE TABLE #EXCEPTIONS	(
ID_RECV						BIGINT
							)

INSERT INTO #ACCTS (
ID_SA			
,ID_CRAC		
,EXTERNAL_SA_ID	
,CD_BUSE		
,CD_ATRO		
,BRAND_DESCR	
,TYP			
,SECTOR			
)

SELECT
SA.ID			
,CA.ID		
,SA.EXTERNAL_SA_ID	
,SA.CD_BUSE		
,BRD.CD_ATRO		
,BRDE.DESCR
,'DOMM'
,'MASS'

FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_CA_SERV_ACCT			CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT			CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND					BRD
ON CA.CD_BRND = BRD.CD
INNER JOIN
VCRO_BRAND_DESCR	BRDE
ON BRD.CD_BRDE = BRDE.CD
INNER JOIN
VCRO_SERVICE_PLAN			SP
ON SA.ID_SP = SP.ID

WHERE
SA.CD_BUSE IN ('ESU','GSS','TSS')
AND BRD.CD_ATRO NOT IN ('BE','BEG')
AND SP.ID_SPTY IN ('EDK','ESD','GSD','GSP','TDB')
AND SA.TRUE_BAL_AMT > '0'

CREATE INDEX ACCTS ON #ACCTS (ID_SA)

UPDATE #ACCTS

SET #ACCTS.FIN_LIVE_IND = FL.STATUS
FROM (
SELECT CA.ID, CASE WHEN MAX(SA.DISP_END_DT) > GETDATE() THEN 'LIVE' ELSE 'FINALLED' END STATUS
FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_CA_SERV_ACCT			CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT			CA
ON CASA.ID_CRAC = CA.ID
GROUP BY
CA.ID
) FL
WHERE #ACCTS.ID_CRAC = FL.ID

INSERT INTO #EXCEPTIONS

SELECT DISTINCT
FT.ID_RECV_01

FROM
VCRO_SA_STATEMENT																			SAST
INNER JOIN
VCRO_FIN_ENTRY																				FE
ON SAST.ID_SA = FE.ID_SA AND SAST.SEQ_NUM = FE.SEQ_NUM_SASM
INNER JOIN
VCRO_FIN_TRANS																				FT
ON FE.ID_SA = FT.ID_SA_FE_01 AND FE.ID = FT.ID_FE_01 AND FE.CD_FAAT_01 = FT.CD_FAAT_01

WHERE
SAST.STAT_CD = 'E'

CREATE INDEX EXCEPTIONS ON #EXCEPTIONS (ID_RECV)

INSERT INTO #RECEIVABLES

SELECT
RECV.ID
,RECV.ID_SA			
,RECV.ID_PPLA		
,CASE
	WHEN DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '0' AND '91' THEN 'A__0 TO 3 MTHS'
	WHEN DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '92' AND '182' THEN 'B__4 TO 6 MTHS'					
	WHEN DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '183' AND '274' THEN 'C__7 TO 9 MTHS'					
	WHEN DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '274' AND '365' THEN 'D__10 TO 12 MTHS'						
	ELSE 'E__OVER 12 MTHS' END					
,CASE			
	WHEN DATEDIFF(M,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '0' AND '6' THEN 'ACTIVE'
	ELSE 'AGED' END	
,CASE
	WHEN DATEDIFF(D,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '0' AND '30' THEN 'A: 0 TO 30 DAYS'	
	WHEN DATEDIFF(D,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '31' AND '60' THEN 'B; 31 TO 60 DAYS'				
	WHEN DATEDIFF(D,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '61' AND '90' THEN 'C: 61 TO 90 DAYS'				
	WHEN DATEDIFF(D,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '91' AND '120' THEN 'D: 91 TO 120 DAYS'					
	ELSE 'E: OVER 121 DAYS' END					
,CASE			
	WHEN DATEDIFF(D,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '0' AND '60' THEN 'ACTIVE'			
	ELSE 'AGED' END	
,CAST(RECV.CUR_BAL_AMT/1000000 AS DECIMAL(11,8))	
,(SELECT YR_NUM FROM VCRO_ACCT_PERIOD WHERE TYP = 'GL' AND GETDATE() BETWEEN STRT_DT AND END_DT)
,(SELECT PERD_NUM FROM VCRO_ACCT_PERIOD WHERE TYP = 'GL' AND GETDATE() BETWEEN STRT_DT AND END_DT)

FROM
VCRO_RECEIVABLE				RECV

WHERE
RECV.CUR_BAL_AMT > '0'
AND RECV.ID_SA IN (SELECT ID_SA FROM #ACCTS)
AND RECV.ID NOT IN (SELECT ID_RECV FROM #EXCEPTIONS)

CREATE INDEX RECV ON #RECEIVABLES (ID_RECV, ID_SA, ID_PPLA)


SELECT
ACCTS.TYP				"TYPE"
,ACCTS.SECTOR			"SECTOR"
,RECV.RUN_YEAR			"FIN_YEAR"
,RECV.RUN_PERIOD -1		"FIN_MONTH"
,ACCTS.CD_BUSE
,RTRIM(ACCTS.FIN_LIVE_IND)	FIN_LIVE_IND
,CASE
	WHEN CC.CLO_DT >= GETDATE() AND PSPM.CD_PMET IS NULL AND PMI.CODE_PMED IS NULL THEN 'COLLECTION CASE'
	ELSE '' END	COLLECTION_CASE
,CASE
	WHEN PSPM.CD_PMET = 'DDB' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'DCA' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'DDV' THEN 'QTLY DD'					
	WHEN PSPM.CD_PMET = 'DDA' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'CCA' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'DCV' THEN 'QTLY DD'					
	WHEN PSPM.CD_PMET = 'SOR' THEN 'MTHLY DD/SO'		
	WHEN PSPM.CD_PMET IN ('UNS','') OR PSPM.CD_PMET IS NULL THEN ''					
	ELSE PSPM.CD_PMET END		PAYMENT_METHOD
,CASE
	WHEN PMI.CODE_PMED='ATP' THEN 'ATP'					
	WHEN PMI.CODE_PMED='SMT' THEN 'ATP'					
	WHEN PMI.CODE_PMED='BKT' THEN 'ATP'					
	WHEN PMI.CODE_PMED='SWP' THEN 'ATP'					
	WHEN PMI.CODE_PMED='KEY' THEN 'KEY'					
	WHEN PMI.CODE_PMED='PNC' THEN 'KEY'
	WHEN PMI.CODE_PMED IS NULL THEN ''					
	ELSE PMI.CODE_PMED END		ARRANGEMENT
,CASE					
	WHEN PP.CODE_PPTY IN ('KBM','TKM','SPG') THEN 'PREPAYMENT'					
	ELSE ''	END					PAY_TYPE
,RTRIM(RECV.AGE_QT)				AGE_QT
,RTRIM(RECV.AGED_ACTIVE_QT)			AGED_ACTIVE_QT
,RTRIM(RECV.AGE_MO)					AGE_MO
,RTRIM(RECV.AGED_ACTIVE_MO)			AGED_ACTIVE_MO
,ACCTS.BRAND_DESCR
,SUM(RECV.CUR_BAL_AMT)	DEBT

FROM
#ACCTS					ACCTS
INNER JOIN
#RECEIVABLES			RECV
ON ACCTS.ID_SA = RECV.ID_SA
LEFT OUTER JOIN
VCRO_PAYMENT_PLAN			PP
ON RECV.ID_PPLA = PP.ID
LEFT OUTER JOIN (
SELECT DISTINCT ID_PPLA, MAX(NUM_PSCH) NUM_PSCH FROM VCRO_PAYMENT_SCHED GROUP BY ID_PPLA
) AS PS
ON PP.ID = PS.ID_PPLA
LEFT OUTER JOIN (
SELECT DISTINCT ID_PPLA, CD_PMET, MAX(NUM_PSCH) NUM_PSCH FROM VCRO_PS_PYMT_MTHD GROUP BY ID_PPLA, CD_PMET
) AS PSPM
ON PS.ID_PPLA = PSPM.ID_PPLA AND PS.NUM_PSCH = PSPM.NUM_PSCH
LEFT OUTER JOIN (
SELECT DISTINCT ID_PPLA, CODE_PMED, MAX(NUM_PSCH) NUM_PSCH FROM VCRO_PAY_MED_ISSUE GROUP BY ID_PPLA, CODE_PMED
) AS PMI
ON PS.ID_PPLA = PMI.ID_PPLA AND PS.NUM_PSCH = PMI.NUM_PSCH
LEFT OUTER JOIN (
SELECT DISTINCT ID_CRAC, MAX(CLO_DT) CLO_DT FROM VCRO_COLL_CASE GROUP BY ID_CRAC
) AS CC
ON ACCTS.ID_CRAC = CC.ID_CRAC

GROUP BY
ACCTS.TYP		
,ACCTS.SECTOR	
,RECV.RUN_YEAR	
,RECV.RUN_PERIOD
,ACCTS.CD_BUSE
,ACCTS.FIN_LIVE_IND
,CASE
	WHEN CC.CLO_DT >= GETDATE() AND PSPM.CD_PMET IS NULL AND PMI.CODE_PMED IS NULL THEN 'COLLECTION CASE'
	ELSE '' END	
,CASE
	WHEN PSPM.CD_PMET = 'DDB' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'DCA' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'DDV' THEN 'QTLY DD'					
	WHEN PSPM.CD_PMET = 'DDA' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'CCA' THEN 'MTHLY DD/SO'					
	WHEN PSPM.CD_PMET = 'DCV' THEN 'QTLY DD'					
	WHEN PSPM.CD_PMET = 'SOR' THEN 'MTHLY DD/SO'		
	WHEN PSPM.CD_PMET IN ('UNS','') OR PSPM.CD_PMET IS NULL THEN ''					
	ELSE PSPM.CD_PMET END		
,CASE
	WHEN PMI.CODE_PMED='ATP' THEN 'ATP'					
	WHEN PMI.CODE_PMED='SMT' THEN 'ATP'					
	WHEN PMI.CODE_PMED='BKT' THEN 'ATP'					
	WHEN PMI.CODE_PMED='SWP' THEN 'ATP'					
	WHEN PMI.CODE_PMED='KEY' THEN 'KEY'					
	WHEN PMI.CODE_PMED='PNC' THEN 'KEY'
	WHEN PMI.CODE_PMED IS NULL THEN ''					
	ELSE PMI.CODE_PMED END		
,CASE					
	WHEN PP.CODE_PPTY IN ('KBM','TKM','SPG') THEN 'PREPAYMENT'					
	ELSE ''	END						
,RECV.AGE_QT
,RECV.AGED_ACTIVE_QT
,RECV.AGE_MO
,RECV.AGED_ACTIVE_MO
,ACCTS.BRAND_DESCR