SELECT
PORT.SMART
,COUNT(DISTINCT EACAA.CORE_MPAN_MPNT)

FROM
VCRO_EAC_AA											EACAA
INNER JOIN
MISUserData.[UK\PB32946].PORTFOLIO_FORECASTING		PORT
ON EACAA.CORE_MPAN_MPNT = PORT.CORE_MPAN_MPNT

WHERE
EACAA.DISP_CALC_TS BETWEEN '2020-09-01' AND '2020-09-30'
AND EACAA.ANNLSD_ADVNC IS NOT NULL
AND EACAA.WITHDRAWN_IND = 'N'

GROUP BY
PORT.SMART



SELECT
SUPPLIER_TYPE
,SMART
,COUNT(CORE_MPAN_MPNT)

FROM
MISUserData.[UK\PB32946].PORTFOLIO_FORECASTING

GROUP BY
SUPPLIER_TYPE
,SMART