SELECT
FCPT.YR_NUM_ACPE_01
,FCPT.PERD_NUM_ACPE_01
,FC.GL_CODE
,FC.GL_CD_CATGRY
,COALESCE(FCPT.DEBIT_TOT_AMT,0)		DEBIT_TOT_AMT
,COALESCE(FCPT.CREDIT_TOT_AMT,0)	CREDIT_TOT_AMT

FROM
VCRO_FC_PERIOD_TOT					FCPT
INNER JOIN
VCRO_FIN_CODE						FC
ON FCPT.DBID_FC_01 = FC.DBID

WHERE
FCPT.YR_NUM_ACPE_01 = '2020'
AND FC.GL_CODE LIKE '% 90%'
AND FCPT.PERD_NUM_ACPE_01 BETWEEN '1' AND '9'