SELECT
FC.GL_CODE
,FC.DESCR
,CASE
	WHEN SUM(COALESCE(FCPT.DEBIT_TOT_AMT,'0'))-SUM(COALESCE(FCPT.CREDIT_TOT_AMT,'0')) > '0' 
	THEN ABS(SUM(COALESCE(FCPT.DEBIT_TOT_AMT,'0'))-SUM(COALESCE(FCPT.CREDIT_TOT_AMT,'0')))
	ELSE '0' END																									
,CASE
	WHEN SUM(COALESCE(FCPT.DEBIT_TOT_AMT,'0'))-SUM(COALESCE(FCPT.CREDIT_TOT_AMT,'0')) < '0' 
	THEN ABS(SUM(COALESCE(FCPT.DEBIT_TOT_AMT,'0'))-SUM(COALESCE(FCPT.CREDIT_TOT_AMT,'0')))
	ELSE '0' END

FROM
VCRO_FC_PERIOD_TOT					FCPT
INNER JOIN
VCRO_FIN_CODE						FC
ON FCPT.DBID_FC_01 = FC.DBID

WHERE
FCPT.SEQ_NUM_01 = '5659'
AND FC.GL_CODE LIKE '% 9%'
AND FCPT.PERD_NUM_ACPE_01 = '08'

GROUP BY
FC.GL_CODE
,FC.DESCR

