USE tempdb
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#BILLS') AND TYPE = 'U') DROP TABLE #BILLS
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#FINANCIALS') AND TYPE = 'U') DROP TABLE #FINANCIALS

USE MIS
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @MONTHSTART																				DATETIME
DECLARE @MONTHEND																				DATETIME

SET @MONTHSTART = ('2020-05-01 00:00:00.000')
SET @MONTHEND = ('2020-05-31 23:59:59.998')

CREATE TABLE #BILLS(
ID_SA																							BIGINT
,SEQ_NUM_SASM																					SMALLINT
,EXTERNAL_SA_ID																					INT
,CD_BUSE																						CHAR(3)
,ID_BLFR_01																						CHAR(2)
,CRET_DT																						DATETIME
,ID_SP																							CHAR(5)
,BILG_PERD																						VARCHAR(30)
,BILG_STRT_DT																					DATETIME
,BILG_END_DT																					DATETIME
)

CREATE TABLE #FINANCIALS(
ID_SA																							BIGINT
,SEQ_NUM_SASM																					SMALLINT
,BLLG_DESCR_SPCO																				VARCHAR(30)
,SP_PLN_CMPNT_CD																				CHAR(10)
,RATE_APPLIED																					DECIMAL(14,6)
,[DAYS]																							DECIMAL(11,2)
,USAGE																							DECIMAL(11,2)
,AMT																							DECIMAL(11,2)
)

CREATE INDEX BILLS ON #BILLS (ID_SA, SEQ_NUM_SASM)

CREATE INDEX BILLS ON #FINANCIALS (ID_SA, SEQ_NUM_SASM)


INSERT INTO #BILLS (
ID_SA
,SEQ_NUM_SASM
,EXTERNAL_SA_ID
,CD_BUSE
,ID_BLFR_01
,CRET_DT
,ID_SP
,BILG_PERD
,BILG_STRT_DT
,BILG_END_DT
)

SELECT
SAST.ID_SA
,SAST.SEQ_NUM
,SA.EXTERNAL_SA_ID
,SA.CD_BUSE
,SAST.ID_BLFR_01
,SAST.CRET_DT
,SAST.ID_SP
,BLPE.BILG_PERD
,SAST.BILG_STRT_DT
,SAST.BILG_END_DT

FROM
VCRO_SA_STATEMENT																				SAST
INNER JOIN
VCRO_SERV_ACCT																					SA
ON SAST.ID_SA = SA.ID
INNER JOIN
VCRO_BILLING_PERD																				BLPE
ON SAST.DBID_BLPE = BLPE.DBID
INNER JOIN
VCRO_CA_SERV_ACCT																				CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT																				CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND																						BRD
ON CA.CD_BRND = BRD.CD

WHERE
SAST.STAT_CD NOT IN ('C','V')
AND SAST.TYP_CD in ('R','B')
AND SAST.CRET_DT BETWEEN @MONTHSTART AND @MONTHEND
AND BRD.CD_ATRO NOT IN ('BE','BEG')
AND SA.CD_BUSE IN ('ESU','GSS')

INSERT INTO #FINANCIALS

SELECT
SSPF.ID_SA			
,SSPF.SEQ_NUM_SASM	
,SSPF.BLLG_DESCR_SPCO
,SP_PLN_CMPNT_CD
,SSPF.RATE_APPLIED
,CASE
	WHEN SSPF.BLLG_DESCR_SPCO LIKE 'STANDING%' THEN SSPF.USAGE		
	ELSE '0' END																				[DAYS]
,CASE
	WHEN SSPF.BLLG_DESCR_SPCO LIKE 'STANDING%' THEN '0'		
	ELSE SSPF.USAGE END																			USAGE		
,SSPF.AMT

FROM
VCRO_SAS_SP_FIN																					SSPF			
INNER JOIN
#BILLS																							BILLS
ON SSPF.ID_SA = BILLS.ID_SA AND SSPF.SEQ_NUM_SASM = BILLS.SEQ_NUM_SASM

SELECT
--TOP 1000 *
BILLS.CD_BUSE
,FIN.BLLG_DESCR_SPCO
,FIN.SP_PLN_CMPNT_CD
,FIN.RATE_APPLIED
,SUM(FIN.[DAYS])																				[DAYS]
,SUM(FIN.USAGE)																					USAGE
,SUM(FIN.AMT)																					AMT

FROM
#BILLS																							BILLS
INNER JOIN
#FINANCIALS																						FIN
ON BILLS.ID_SA = FIN.ID_SA AND BILLS.SEQ_NUM_SASM = FIN.SEQ_NUM_SASM

WHERE
FIN.BLLG_DESCR_SPCO NOT LIKE 'FIT%'
AND FIN.BLLG_DESCR_SPCO NOT LIKE 'GD%'
AND FIN.AMT > '0'
AND FIN.BLLG_DESCR_SPCO LIKE '%STANDING%'

GROUP BY
BILLS.CD_BUSE
,FIN.BLLG_DESCR_SPCO
,FIN.SP_PLN_CMPNT_CD
,FIN.RATE_APPLIED

ORDER BY
FIN.RATE_APPLIED ASC
