CREATE TABLE #VAT_BALS (
ID_SA					BIGINT
,EXTERNAL_SA_ID			BIGINT
,DR_CR_ACCOUNT			CHAR(2)
,SA_TRUE_BAL_AMT		DECIMAL(11,2)
,VAT3_VAT_AMOUNT		DECIMAL(11,2)
,VAT3_UNUSED_AMOUNT_1	DECIMAL(11,2)
,VAT3_UNUSED_AMOUNT_2	DECIMAL(11,2)
,VAT3_UNUSED_AMOUNT_3	DECIMAL(11,2)
,VAT3_UNUSED_AMOUNT_4	DECIMAL(11,2)
,VAT3_UNUSED_AMOUNT_5	DECIMAL(11,2)
,VAT1_NET_AMOUNT		DECIMAL(11,2)
,VAT1_VAT_AMOUNT		DECIMAL(11,2)
,VAT1_GROSS_AMOUNT		DECIMAL(11,2)
,VAT1_VAT_COSTED		DECIMAL(11,2)
						)

INSERT INTO #VAT_BALS	(
ID_SA			
,EXTERNAL_SA_ID	
,DR_CR_ACCOUNT	
,SA_TRUE_BAL_AMT
						)

SELECT
SA.ID
,SA.EXTERNAL_SA_ID
,CASE
	WHEN SA.TRUE_BAL_AMT < '0' THEN 'CR'
	ELSE 'DR' END
,SUM(SA.TRUE_BAL_AMT)									

FROM
MISUserData.[UK\PB32946].VCRO_SERV_ACCT_01112020			SA	
INNER JOIN
VCRO_CA_SERV_ACCT											CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT											CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND													BRD
ON CA.CD_BRND = BRD.CD

WHERE
SA.TRUE_BAL_AMT <> '0'
AND BRD.CD_ATRO NOT IN ('BE','BEG','SYSB')

GROUP BY
SA.ID
,SA.EXTERNAL_SA_ID
,CASE
	WHEN SA.TRUE_BAL_AMT < '0' THEN 'CR'
	ELSE 'DR' END


SELECT
VAT3.ID_SA
,SUM(VAT3.VAT_AMOUNT)										VAT_AMOUNT										
,SUM(VAT3.UNUSED_AMOUNT_1)									UNUSED_AMOUNT_1								
,SUM(VAT3.UNUSED_AMOUNT_2)									UNUSED_AMOUNT_2													
,SUM(VAT3.UNUSED_AMOUNT_3)									UNUSED_AMOUNT_3								
,SUM(VAT3.UNUSED_AMOUNT_4)									UNUSED_AMOUNT_4								
,SUM(VAT3.UNUSED_AMOUNT_5)									UNUSED_AMOUNT_5

INTO #VAT3
																	 
FROM
VMI_VAT3_DETAIL_CURRENT										VAT3

WHERE
VAT3.VAT_REG_NUM = 'GB 333 5830 10'

GROUP BY
VAT3.ID_SA


SELECT
VAT1.ID_SA
,SUM(VAT1.NET_AMOUNT)										NET_AMOUNT			
,SUM(VAT1.VAT_AMOUNT)										VAT_AMOUNT			
,SUM(VAT1.GROSS_AMOUNT)										GROSS_AMOUNT			
,SUM(VAT1.VAT_COSTED)										VAT_COSTED

INTO #VAT1

FROM
VMI_VAT1_DETAIL_CURRENT								VAT1
INNER JOIN
MISUserData.[UK\PB32946].VCRO_SERV_ACCT_01112020		SA
ON VAT1.ID_SA = SA.ID

WHERE
VAT1.VAT_REG_NUM = 'GB 333 5830 10'

GROUP BY
VAT1.ID_SA