SELECT
MCC.YR_NUM_ACPE_01
,MCC.PERD_NUM_ACPE_01
,FAIT.DESCR
,MCC.ACCOUNT_CODE
,MCC.COST_CENTRE
,SUM(MCC.TTL_USG)				USAGE
,SUM(MCC.AMT)					AMOUNT

FROM
VMI_SALES_MCC					MCC
INNER JOIN
VCRO_FA_ITEM_TYPE				FAIT
ON MCC.CD_FAIT = FAIT.CD
INNER JOIN
VRT_VCRO_SERV_ACCT				SA
ON MCC.ID_SA = SA.ID

WHERE
MCC.YR_NUM_ACPE_01 = '2021'
AND MCC.PERD_NUM_ACPE_01 <= '02'
AND MCC.CD_FAIT IN ('CCA3','PB40','CSTP','CSTC','PPBC','PPPA','VBD1','E10A','E10B','PRIE','PRIG','PRIO','PUBL','PUBG')
AND MCC.COST_CENTRE LIKE '9%'
AND MCC.ACCOUNT_CODE LIKE '3%'

GROUP BY
MCC.YR_NUM_ACPE_01
,MCC.PERD_NUM_ACPE_01
,FAIT.DESCR
,MCC.ACCOUNT_CODE
,MCC.COST_CENTRE