SELECT		
SA.EXTERNAL_SA_ID			
,RECV.ID_SA
,SUM(RECV.AMT)															AMOUNT			
			
FROM			
VMI_AGED_RECV															RECV
INNER JOIN
VCRO_SERV_ACCT															SA
ON RECV.ID_SA = SA.ID
INNER JOIN
VCRO_SERVICE_PLAN														SP
ON SA.ID_SP = SP.ID
			
WHERE			
RECV.CD_ATRO NOT IN ('BE','BEG','SYSB')			
AND RECV.CD_BUSE IN ('ESU','GSS')
AND RECV.AMT < '0'
AND RECV.FIN_LIVE = 'L'

GROUP BY
SA.EXTERNAL_SA_ID			
,RECV.ID_SA		