SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

USE tempdb
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#ACCTS') AND TYPE = 'U') DROP TABLE #ACCTS
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#RECEIVABLES') AND TYPE = 'U') DROP TABLE #RECEIVABLES
USE MIS

CREATE TABLE #ACCTS			(
ID_SA						BIGINT
,ID_CRAC					INT
,EXTERNAL_SA_ID				INT
,CD_BUSE					CHAR(3)
,CD_ATRO					CHAR(4)
,FIN_LIVE_IND				CHAR(8)
,TRUE_BAL_AMT				DECIMAL(11,2)
)

CREATE TABLE #RECEIVABLES	(
ID_RECV						BIGINT	
,ID_SA						BIGINT
,ID_PPLA					BIGINT
,DISP_CRET_DT				DATETIME
,CUR_BAL_AMT				DECIMAL(11,2)
							)

INSERT INTO #ACCTS (
ID_SA			
,ID_CRAC		
,EXTERNAL_SA_ID	
,CD_BUSE		
,CD_ATRO		
,TRUE_BAL_AMT
)

SELECT
SA.ID			
,CA.ID		
,SA.EXTERNAL_SA_ID	
,SA.CD_BUSE		
,BRD.CD_ATRO	
,SA.TRUE_BAL_AMT

FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_CA_SERV_ACCT			CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT			CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND					BRD
ON CA.CD_BRND = BRD.CD
INNER JOIN
VCRO_BRAND_DESCR	BRDE
ON BRD.CD_BRDE = BRDE.CD
INNER JOIN
VCRO_SERVICE_PLAN			SP
ON SA.ID_SP = SP.ID

WHERE
SA.CD_BUSE IN ('ESU','GSS')
AND BRD.CD_ATRO NOT IN ('BE','BEG')
AND SP.ID_SPTY IN ('EDK','ESD','GSD','GSP','TDB')
AND SA.TRUE_BAL_AMT <> '0'

CREATE INDEX ACCTS ON #ACCTS (ID_SA)

UPDATE #ACCTS

SET #ACCTS.FIN_LIVE_IND = FL.STATUS
FROM (
SELECT CA.ID, CASE WHEN MAX(SA.DISP_END_DT) > GETDATE() THEN 'LIVE' ELSE 'FINALLED' END STATUS
FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_CA_SERV_ACCT			CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT			CA
ON CASA.ID_CRAC = CA.ID
GROUP BY
CA.ID
) FL
WHERE #ACCTS.ID_CRAC = FL.ID

INSERT INTO #RECEIVABLES

SELECT
RECV.ID
,RECV.ID_SA			
,RECV.ID_PPLA		
,RECV.DISP_CRET_DT					
,RECV.CUR_BAL_AMT	

FROM
VCRO_RECEIVABLE				RECV

WHERE
RECV.CUR_BAL_AMT <> '0'
AND RECV.ID_SA IN (SELECT ID_SA FROM #ACCTS)

CREATE INDEX RECV ON #RECEIVABLES (ID_RECV, ID_SA, ID_PPLA)


SELECT
a.[dr]
,a.[age]
,a.[fin_live_ind]
,a.[cd_buse]
,sum(a.[debt])

from(
select
CASE
	WHEN ACCTS.TRUE_BAL_AMT > '0' THEN 'DEBITS' ELSE 'CREDITS'
	END 'dr'
,CASE
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) <= '34' THEN '1. Live 0-34 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '35' AND '60' THEN '2. Live 35-60 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '61' AND '90' THEN '3. Live 61-90 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '91' AND '360' THEN '4. Live 91-360 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '361' AND '720' THEN '5. Live 361-720 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) > '720' THEN '6. Live > 720 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) < '3' THEN '7. Lost 1-2 Months'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '3' AND '6' THEN '8. Lost 3-6 Months'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '7' AND '12' THEN '9. Lost 7-12 Months'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) > '12' THEN '10. Lost 12 Months+'
	ELSE 'UNKNOWN'
	END 'age'
,RTRIM(ACCTS.FIN_LIVE_IND)	FIN_LIVE_IND
,ACCTS.CD_BUSE
,SUM(RECV.CUR_BAL_AMT)	DEBT

FROM
#ACCTS					ACCTS
INNER JOIN
#RECEIVABLES			RECV
ON ACCTS.ID_SA = RECV.ID_SA

GROUP BY
accts.TRUE_BAL_AMT
,ACCTS.CD_BUSE
,ACCTS.FIN_LIVE_IND
,CASE
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) <= '34' THEN '1. Live 0-34 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '35' AND '60' THEN '2. Live 35-60 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '61' AND '90' THEN '3. Live 61-90 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '91' AND '360' THEN '4. Live 91-360 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '361' AND '720' THEN '5. Live 361-720 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'LIVE' AND DATEDIFF(DAY,RECV.DISP_CRET_DT,GETDATE()) > '720' THEN '6. Live > 720 Days'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) < '3' THEN '7. Lost 1-2 Months'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '3' AND '6' THEN '8. Lost 3-6 Months'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) BETWEEN '7' AND '12' THEN '9. Lost 7-12 Months'
	WHEN ACCTS.FIN_LIVE_IND = 'FINALLED' AND DATEDIFF(MONTH,RECV.DISP_CRET_DT,GETDATE()) > '12' THEN '10. Lost 12 Months+'
	ELSE 'UNKNOWN'
	END				
	) as a

	group by
	a.[dr]
,a.[age]
,a.[fin_live_ind]
,a.[cd_buse]