SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

USE tempdb
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#ACCTS') AND TYPE = 'U') DROP TABLE #ACCTS
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#RECEIVABLES') AND TYPE = 'U') DROP TABLE #RECEIVABLES
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#EXCEPTIONS') AND TYPE = 'U') DROP TABLE #EXCEPTIONS
USE MIS

CREATE TABLE #ACCTS			(
ID_SA						BIGINT
,ID_CRAC					INT
,EXTERNAL_SA_ID				INT
,CD_BUSE					CHAR(3)
,CD_ATRO					CHAR(4)
,FIN_LIVE_IND				CHAR(8)
,ID_ADDR					INT
)

INSERT INTO #ACCTS (
ID_SA			
,ID_CRAC		
,EXTERNAL_SA_ID	
,CD_BUSE		
,CD_ATRO
,ID_ADDR
)

SELECT
SA.ID			
,CA.ID		
,SA.EXTERNAL_SA_ID	
,SA.CD_BUSE		
,BRD.CD_ATRO	
,CA.ID_ADDR

FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_CA_SERV_ACCT			CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT			CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND					BRD
ON CA.CD_BRND = BRD.CD
INNER JOIN
VCRO_BRAND_DESCR	BRDE
ON BRD.CD_BRDE = BRDE.CD
INNER JOIN
VCRO_SERVICE_PLAN			SP
ON SA.ID_SP = SP.ID

WHERE
SA.CD_BUSE IN ('ESU','GSS','TSS')
AND BRD.CD_ATRO NOT IN ('BE','BEG')
AND SP.ID_SPTY IN ('EDK','ESD','GSD','GSP','TDB')
AND SA.TRUE_BAL_AMT > '0'

CREATE INDEX ACCTS ON #ACCTS (ID_SA)

UPDATE #ACCTS

SET #ACCTS.FIN_LIVE_IND = FL.STATUS
FROM (
SELECT CA.ID, CASE WHEN MAX(SA.DISP_END_DT) > GETDATE() THEN 'LIVE' ELSE 'FINALLED' END STATUS
FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_CA_SERV_ACCT			CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT			CA
ON CASA.ID_CRAC = CA.ID
GROUP BY
CA.ID
) FL
WHERE #ACCTS.ID_CRAC = FL.ID

SELECT
PORT.ID_SA
,PORT.EXTERNAL_SA_ID
,PORT.ID_ADDR
,ADDR.NUM_POCO

FROM
#ACCTS	PORT
INNER JOIN
VCRO_ADDRESS										ADDR
ON PORT.ID_ADDR = ADDR.ID

WHERE
PORT.ID_SA IS NOT NULL


select
count(id_sa)
from #accts
