SELECT
PORT.ID_SA
,PORT.EXTERNAL_SA_ID
,PORT.ID_ADDR
,ADDR.NUM_POCO

FROM
MISUserData.[UK\DC43967].PORTFOLIO_FOR_SMART_WASHES	PORT
INNER JOIN
VCRO_ADDRESS										ADDR
ON PORT.ID_ADDR = ADDR.ID

WHERE
PORT.ID_SA IS NOT NULL