SELECT
SA.ID								COUNT_ACCTS
,SUM(UB.UNBILLED_STANDING_CHARGE)	UNBILLED_SC
,SUM(UB.SINGLE_RATE_UNBILLED)		UNBILLED_USG_SR
,SUM(UB.MULTI_RATE_R1_UNBILLED)		UNBILLED_USG_MR1
,SUM(UB.MULTI_RATE_R2_UNBILLED)		UNBILLED_USG_MR2
,SUM(SA.TRUE_BAL_AMT)		BALANCE
,(SUM(UB.UNBILLED_STANDING_CHARGE)+SUM(UB.SINGLE_RATE_UNBILLED)+SUM(UB.MULTI_RATE_R1_UNBILLED)+SUM(UB.MULTI_RATE_R2_UNBILLED)+SUM(SA.TRUE_BAL_AMT))	TRUE_BAL

INTO #PP_ANALYSIS

FROM
VCRO_SERV_ACCT				SA
INNER JOIN
VCRO_SERVICE_PLAN			SP
ON SA.ID_SP = SP.ID
INNER JOIN
MISUserData.[UK\PB32946].UNBILLED_02092020	UB
ON SA.EXTERNAL_SA_ID = UB.EXTERNAL_SA_ID

WHERE
SA.TRUE_BAL_AMT <> '0'
AND SP.ID_SPTY IN ('GSP','EDK','SPG')

GROUP BY
SA.ID

SELECT
COUNT(COUNT_ACCTS)						COUNT_ACCOUNTS
,SUM(TRUE_BAL)						BALANCE

FROM 
#PP_ANALYSIS

WHERE
TRUE_BAL < '0'