SELECT
DWO.YEAR
,DWO.PERIOD
,SUM(DWO.AMT)*-1				AMOUNT

FROM
VMI_DEBT_WRITE_OFF2017			DWO
INNER JOIN
VCRO_SERV_ACCT					SA
ON DWO.ID_SA = SA.ID
INNER JOIN
VCRO_SERVICE_PLAN				SP
ON SA.ID_SP = SP.ID

WHERE
SP.ID_SPTY IN ('EDK','GSP')
AND DWO.CD_FAIT IN ('DWO','BDR')

GROUP BY
DWO.YEAR
,DWO.PERIOD