SELECT 
SA.EXTERNAL_SA_ID
,FC.GL_CODE
,BRD.CD_ATRO
,FT.AMT

FROM
VCRO_SERV_ACCT						SA
INNER JOIN
VCRO_CA_SERV_ACCT					CASA
ON SA.ID = CASA.ID_SA
INNER JOIN
VCRO_CUST_ACCOUNT					CA
ON CASA.ID_CRAC = CA.ID
INNER JOIN
VCRO_BRAND							BRD
ON CA.CD_BRND = BRD.CD
INNER JOIN
VCRO_BRAND_DESCR	BRDE
ON BRD.CD_BRDE = BRDE.CD
INNER JOIN
VCRO_SERVICE_PLAN					SP
ON SA.ID_SP = SP.ID
INNER JOIN
VCRO_FIN_TRANS						FT
ON SA.ID = FT.ID_SA_FE_01
INNER JOIN
VCRO_FIN_CODE						FC
ON FT.DBID_FC_01 = FC.DBID

WHERE
FT.YR_NUM_ACPE_01 = '2020'
AND FT.PERD_NUM_ACPE_01 = '09'
AND FC.GL_CODE LIKE '1621005 %'
AND FC.GL_CODE LIKE '% 2001'