SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @DATE																AS VARCHAR(10)
DECLARE @DECDATE															AS DECIMAL(20,6)
DECLARE @DATE2																AS VARCHAR(25)
DECLARE @END_DT																AS VARCHAR(10)

SET @DATE =                      											CONVERT(VARCHAR(10),DATEADD(YYYY,0,GETDATE()),121)
SET @DATE2 =                   												CONVERT(VARCHAR(MAX),DATEADD(YYYY,0,CURRENT_TIMESTAMP),21)
SET @DECDATE =																REPLACE(REPLACE(REPLACE(@DATE2,'-',''),' ',''),':','')
SET @END_DT =																'2020-06-01'  --DEFINE DATE YOU WISH TO STOP AT

SELECT 
PAYD.DUE_DT
,SUM(PAYD.AMT)																AMT_TO_BE_PAID

FROM
VRT_VCRO_CUST_ACCOUNT														DRVR
INNER JOIN
VCRO_PAYMENT_PLAN															PAYN
ON PAYN.ID_CRAC=DRVR.ID
INNER JOIN
VCRO_PAYMENT_SCHED															PSCH
ON PSCH.ID_PPLA=PAYN.ID
INNER JOIN
VCRO_PS_AMOUNT																PAYD
ON PAYD.ID_PPLA_01=PSCH.ID_PPLA AND PAYD.NUM_PSCH_01=PSCH.NUM_PSCH

WHERE 
PAYN.CLOSE_DT>@DATE
AND PAYN.ACTV_DT<@DATE
AND PSCH.CD_FIST='A'
AND PAYD.CD_FIST='Y'
AND PAYD.DUE_DT BETWEEN @DATE AND @END_DT

GROUP BY 
PAYD.DUE_DT