SELECT
RECV.FIN_YEAR
,RECV.FIN_MONTH
,CASE
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M0' THEN '1. LIVE 0-30 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M1' THEN '2. LIVE 31-60 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M2' THEN '3. LIVE 61-90 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M3' THEN '4. LIVE 91-360 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE IN ('Q0','Q1','Q2','Q3','Q4') AND RECV.YR_AGE = 'Y0' THEN '4. LIVE 91-360 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE = 'Q5' AND RECV.YR_AGE IN('Y0','Y1') THEN '5. LIVE 316-720 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.YR_AGE IN('Y2','Y3','Y4','Y5') THEN '6. LIVE >720 DAYS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE IN ('M0','M1') THEN '7. LOST 1-2 MONTHS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE IN ('M2','M3','M4') AND RECV.QT_AGE IN ('Q0','Q1','Q2') THEN '8. LOST 3-6 MONTHS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE IN ('Q3','Q4') THEN '9. LOST 7-12 MONTHS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE = 'Q5' AND RECV.YR_AGE IN ('Y0','Y1','Y2','Y3','Y4','Y5') THEN '10. LOST 12 MONTHS+'
ELSE RECV.MO_AGE
END																																							AGE
,SUM(RECV.DB_FIN_TRANS_AMT)																																	DR_AMT

FROM
VMI_SUM_AGED_RECV																																			RECV

WHERE
RECV.CD_BUSE IN ('ESU','GSS')
AND RECV.CD_ATRO NOT IN ('BE','BEG')
AND RECV.FIN_YEAR <= '2021'

GROUP BY
RECV.FIN_YEAR
,RECV.FIN_MONTH
,CASE
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M0' THEN '1. LIVE 0-30 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M1' THEN '2. LIVE 31-60 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M2' THEN '3. LIVE 61-90 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M3' THEN '4. LIVE 91-360 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE IN ('Q0','Q1','Q2','Q3','Q4') AND RECV.YR_AGE = 'Y0' THEN '4. LIVE 91-360 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE = 'Q5' AND RECV.YR_AGE IN('Y0','Y1') THEN '5. LIVE 316-720 DAYS'
WHEN RECV.FIN_LIVE = 'L' AND RECV.YR_AGE IN('Y2','Y3','Y4','Y5') THEN '6. LIVE >720 DAYS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE IN ('M0','M1') THEN '7. LOST 1-2 MONTHS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE IN ('M2','M3','M4') AND RECV.QT_AGE IN ('Q0','Q1','Q2') THEN '8. LOST 3-6 MONTHS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE IN ('Q3','Q4') THEN '9. LOST 7-12 MONTHS'
WHEN RECV.FIN_LIVE = 'F' AND RECV.MO_AGE = 'M4' AND RECV.QT_AGE = 'Q5' AND RECV.YR_AGE IN ('Y0','Y1','Y2','Y3','Y4','Y5') THEN '10. LOST 12 MONTHS+'
ELSE RECV.MO_AGE
END																																					