USE TEMPDB
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID ('#FINTRANS') AND TYPE = 'U') DROP TABLE #FINTRANS
USE MIS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @YEAR CHAR(4)
DECLARE @PERIOD CHAR(2)
SET @YEAR = '2021'
SET @PERIOD = '04'

CREATE TABLE #FINTRANS (
YR_NUM_ACPE_01				CHAR(4)
,PERD_NUM_ACPE_01			SMALLINT
,SEQ_NUM_FCPT_01			SMALLINT
,ID_SA_FE_01				BIGINT
,CD_FAIT					CHAR(4)
,UNACCOUNTED_VAT			CHAR(1)
,ORIGINAL_AMT				DECIMAL(11,2)
,TOTAL_WRITTEN_OFF			DECIMAL(11,2)
,DERIVED_VAT_TO_RECLAIM		DECIMAL(11,2)
,VAT_WRITTEN_OFF			DECIMAL(11,2)
)

INSERT INTO #FINTRANS (
YR_NUM_ACPE_01			
,PERD_NUM_ACPE_01		
,SEQ_NUM_FCPT_01		
,ID_SA_FE_01			
,CD_FAIT				
,ORIGINAL_AMT			
,TOTAL_WRITTEN_OFF		
,DERIVED_VAT_TO_RECLAIM	
,VAT_WRITTEN_OFF		
)

SELECT
FT.YR_NUM_ACPE_01
,FT.PERD_NUM_ACPE_01
,FT.SEQ_NUM_FCPT_01
,FT.ID_SA_FE_01
,CD_FAIT
,FT.AMT																		
,CASE WHEN CD_FAIT IN ('DWO','BDR') THEN SUM(FT.AMT) END					
,CASE WHEN CD_FAIT IN ('DWO','BDR') THEN SUM(FT.AMT)-(SUM(FT.AMT)/1.05) END	
,CASE WHEN CD_FAIT IN ('VWO','VWR') THEN SUM(FT.AMT) END						

FROM
VCRO_FIN_TRANS	FT
INNER JOIN
VRT_VCRO_SERV_ACCT			ACCTS
ON FT.ID_SA_FE_01 = ACCTS.ID AND FT.CD_FAAT_01 = 'MCC'

WHERE
FT.YR_NUM_ACPE_01 = @YEAR
AND FT.PERD_NUM_ACPE_01 = @PERIOD
AND FT.CD_FAIT IN ('DWO','BDR','VWO','VWR')

GROUP BY
FT.YR_NUM_ACPE_01
,FT.PERD_NUM_ACPE_01
,FT.SEQ_NUM_FCPT_01
,FT.ID_SA_FE_01
,CD_FAIT
,FT.AMT	

CREATE INDEX #FINTRANS ON #FINTRANS(ID_SA_FE_01,SEQ_NUM_FCPT_01,CD_FAIT)

UPDATE #FINTRANS
SET #FINTRANS.UNACCOUNTED_VAT = UA_VAT.UNACCOUNTED_VAT
FROM
(
SELECT
FT.ID_SA_FE_01
,FT.SEQ_NUM_FCPT_01
,CASE WHEN SUM(FT.VAT_WRITTEN_OFF) < SUM(FT.DERIVED_VAT_TO_RECLAIM) THEN 'N' ELSE 'Y' END	UNACCOUNTED_VAT
FROM
#FINTRANS AS FT

GROUP BY
FT.ID_SA_FE_01
,FT.SEQ_NUM_FCPT_01
) AS UA_VAT
WHERE
#FINTRANS.ID_SA_FE_01 = UA_VAT.ID_SA_FE_01 AND #FINTRANS.SEQ_NUM_FCPT_01 = UA_VAT.SEQ_NUM_FCPT_01

SELECT
FT.YR_NUM_ACPE_01
,FT.PERD_NUM_ACPE_01		
,SUM(FT.TOTAL_WRITTEN_OFF)			TOTAL_WRITTEN_OFF
,SUM(FT.VAT_WRITTEN_OFF)			VAT_WRITTEN_OFF
,SUM(FT.DERIVED_VAT_TO_RECLAIM)		DERIVED_VAT_TO_RECLAIM

FROM
#FINTRANS		FT	

WHERE
FT.UNACCOUNTED_VAT = 'Y'

GROUP BY
FT.YR_NUM_ACPE_01
,FT.PERD_NUM_ACPE_01