SELECT 
COUNT(DISTINCT EXTERNAL_SA_ID)
,SUM(TEMP.AMT)

FROM
(
SELECT
SA.EXTERNAL_SA_ID
,SAST.SEQ_NUM
,ROUND(SAST.TTL_NEW_CHG_EX_VAT * 1.05,2)								AMT
,SAST.CRET_DT
,CST.SENT_DT

FROM
VCRO_SA_STATEMENT														SAST
INNER JOIN
VCRO_SERV_ACCT															SA
ON SAST.ID_SA = SA.ID
INNER JOIN
VCRO_CA_STATEMENT														CST
ON SAST.ID_CRAC = CST.ID_CRAC AND SAST.SEQ_NUM_CRST = CST.SEQ_NUM
INNER JOIN
VCRO_SERVICE_PLAN														SP
ON SA.ID_SP = SP.ID

WHERE
SAST.CRET_DT <= '2019-06-30'
AND CST.SENT_DT > '2019-06-30'
--AND CST.SENT_DT BETWEEN '2019-07-01' AND '2019-07-31'
AND SA.CD_BUSE IN ('ESU','GSS')
AND SP.ID_SPTY IN ('EDK','ESD','GSD','GSP')
) 
AS TEMP  