-- age vintages
-- last transaction type
-- cleaned up vat3
-- summary data

SELECT
VAT3.ID_SA
,VAT3.EXTERNAL_SA_ID
,CASE 
	WHEN SA.DISP_END_DT <= GETDATE() THEN 'Y' 
	ELSE 'N'
	END														FINAL_ACCT_IND
,CASE
	WHEN SA.DISP_END_DT	<= GETDATE() THEN SA.DISP_END_DT
	ELSE '' 
	END														SA_END_DATE
,VAT3.NET_AMOUNT
,VAT3.VAT_AMOUNT
,SA.TRUE_BAL_AMT

INTO #PROBACCTS

FROM
VMI_VAT3_DETAIL_CURRENT										VAT3
LEFT OUTER JOIN
VCRO_SERV_ACCT												SA
ON VAT3.ID_SA = SA.ID

WHERE
VAT3.CD_ATRO NOT IN ('BE','BEG')
AND VAT3.CD_BUSE IN ('GSS','ESU')
AND SA.TRUE_BAL_AMT = '0'

CREATE INDEX PROBS ON #PROBACCTS (ID_SA)


SELECT
ACCTS.EXTERNAL_SA_ID
,ACCTS.FINAL_ACCT_IND
,ACCTS.SA_END_DATE
,ACCTS.TRUE_BAL_AMT
,ACCTS.NET_AMOUNT
,ACCTS.VAT_AMOUNT
,MAX(FE.DISP_CREATE_DATE)																						LAST_FINANCIAL_ENTRY_DATE

INTO #PROBACCTS2

FROM
#PROBACCTS																										ACCTS
INNER JOIN
VCRO_FIN_ENTRY																									FE
ON ACCTS.ID_SA = FE.ID_SA

GROUP BY
ACCTS.EXTERNAL_SA_ID
,ACCTS.FINAL_ACCT_IND
,ACCTS.SA_END_DATE
,ACCTS.TRUE_BAL_AMT
,ACCTS.NET_AMOUNT
,ACCTS.VAT_AMOUNT

SELECT
DATEPART(YEAR,LAST_FINANCIAL_ENTRY_DATE)																		[YEAR]
,DATEPART(MONTH,LAST_FINANCIAL_ENTRY_DATE)																		[MONTH]
,COUNT(EXTERNAL_SA_ID)																							COUNT_ACCTS
,SUM(TRUE_BAL_AMT)																								SUM_TRUE_BALANCE_AMT
,SUM(NET_AMOUNT)																								SUM_NET_AMT
,SUM(VAT_AMOUNT)																								SUM_VAT_AMT

FROM
#PROBACCTS2

GROUP BY
DATEPART(YEAR,LAST_FINANCIAL_ENTRY_DATE)	
,DATEPART(MONTH,LAST_FINANCIAL_ENTRY_DATE)