SELECT
MCC.YR_NUM_ACPE_01
,MCC.PERD_NUM_ACPE_01
,FAIT.DESCR
,MCC.ACCOUNT_CODE
,MCC.COST_CENTRE
,SUM(MCC.AMT)																		AMOUNT

FROM
VMI_SALES_MCC																		MCC
INNER JOIN
VCRO_FA_ITEM_TYPE																	FAIT
ON MCC.CD_FAIT = FAIT.CD

WHERE
FAIT.CD IN ('PPBC','PPPA','CCA3','PB40','CSTC','CSTP')
AND MCC.CD_BUSE IN ('ESU','GSS')
AND MCC.CD_ATRO NOT IN ('BE','BEG')
AND MCC.YR_NUM_ACPE_01 = '2021'
AND MCC.PERD_NUM_ACPE_01 = '01'
AND MCC.COST_CENTRE LIKE '9%'

GROUP BY
MCC.YR_NUM_ACPE_01
,MCC.PERD_NUM_ACPE_01
,FAIT.DESCR
,MCC.ACCOUNT_CODE
,MCC.COST_CENTRE